### ISSUE TITLE
New release for providing Symfony 4 support

### ISSUE THREAD

**Issue by adiq** [coduo/php-matcher#120]
It would be great to release new version of php-matcher to provide Symfony 4 support.

**Comment by SpartakusMd** [comment]
Hello @adiq. Do you encounter any issue using it on Symfony 4 as I don't see why someone couln't use it on it.

**Comment by norzechowicz** [comment]
@SpartakusMd I think it's because dependencies in version 2.3 https://github.com/coduo/php-matcher/blob/2.3.0/composer.json as you can see it's a bit different than at master branch where symfony 4.x was added. 
I will draft new release soon, for now you can always use master branch - I'm not going to merge any BC breaks to the master anyway, only new features.

**Comment by norzechowicz** [comment]
https://github.com/coduo/php-matcher/releases/tag/3.0.0 here you go
