### ISSUE TITLE
Invalid json with line breaks in array repeat expander

### ISSUE THREAD

**Issue by Linkinou** [coduo/php-matcher#165]
Hey,
Not sure if it's a bug or I'm doing something wrong.

Given this json and using the JsonMatcher : 
```
    {
        "id": "@number@",
        "name": "@string@",
        "entries": "@array@.repeat({
            \"id\": \"@number@\",
            \"question\": \"@string@\",
            \"answer\": \"@string@\",
            \"os\": \"@*@\"
        })"
    }
```
I got this error : 
`Invalid given JSON of pattern. Unexpected control character found (Exception)`

But with this given json, it works : 
```
    {
        "id": "@number@",
        "name": "@string@",
        "entries": "@array@.repeat({\"id\": \"@number@\", \"question\": \"@string@\", \"answer\": \"@string@\", \"os\": \"@*@\"})"
    }
```

The only thing I've changed is putting the array.repeat content on the same line.

Is that an expected behavior ?

**Comment by norzechowicz** [comment]
Hey, your issue is not really php-matcher related. It's JSON that does not allow multiline strings. 

```json
{
  "id": "@number@",
  "name": "@string@",
  "entries": "valid_json_string"
}
```

This is valid json, ignore the fact that I replaced `"@array@"` with something else. 

Now if you look at:

```
{
  "id": "@number@",
  "name": "@string@",
  "entries": "
      this is multine 
      json string
   "
}
```

This is no longer valid json. You can test those examples here: https://jsonformatter.curiousconcept.com/

However JsonMatcher is already doing some manipulations on JSON's patterns in order to allow something like this:
```
{
    "name": @string@
}
```

It's not valid json (`"` are missing around `@string@`) , but still PHPMatcher can handle that thanks to `\Coduo\PHPMatcher\Matcher\Pattern\Assert\Json::transformPattern` method. What I'm planning to do here is to remove all new lines in that method, thanks to this patter will be become valid JSON for matcher and your example should work fine. 
Expect PR to master shortly.

**Comment by Linkinou** [comment]
That's perfect, thank you @norzechowicz
