### ISSUE TITLE
PHPMatcherConstraint support for errors with html response

### ISSUE THREAD

**Issue by akondas** [coduo/php-matcher#197]
**Problem:**
If you get a very long text in the compared string, it makes it very difficult to debug the console. For example using `PHPMatcherConstraint` with API tests, when response is html (500 response with symfony debug) you will be not able to read it from console:
```bash
bsp;&nbsp;&nbsp;&nbsp;&nbsp;}</span></span></code></li> <li><a class="anchor" name="line599"></a><code><span style="color: var(--highlight-keyword)"></span></span></code></li> <li><a class="anchor" name="line600"></a><code><span style="color: var(--highlight-keyword)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{</span></span></code></li> <li><a class="anchor" name="line601"></a><code><span style="color: var(--highlight-keyword)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;foreach&nbsp;(</span><
```

**Proposal:**
Changes in `PHPMatcherConstraint` that will reduce long string and allow to display error more human friendly :wink: 

```bash
Failed asserting that '<html ... [trimmed]' matches given pattern.
Pattern: '\n
        {\n
            "notify-batch": "https://packagist.org/downloads/",\n
            "providers-url": "/p/%package%$%hash%.json"\n
        }\n
        '
Error: Invalid given JSON of value. Syntax error, malformed JSON
Backtrace: trimmed backtrace.
```

Let me know what you think about it. If it is ok I can introduce MR with required changes.

**Comment by norberttech** [comment]
Yeah I also had this issue couple times but honestly I'm not sure how to create rules for cutting message, I know that I thought about comparing value length with pattern length and trim it only when there is a significant difference. 
In that case, it would need to check the length of the pattern and trim value in error message to that double of that length. 
I was also thinking about detecting HTML and extracting text from it since in test environment 5xx error pages are usually full of details. 
Another option would be detecting Symfony 500 error pages and extracting exception stack trace (that could be helpful). 

I'm thinking about all those options in order to avoid cutting important part of the message in the process. 

Any thoughts?
