### ISSUE TITLE
Type pattern "@...@" is not supported by TextMatcher.

### ISSUE THREAD

**Issue by tentacode** [coduo/php-matcher#432]
Looks like PHPMatcher uses TextMatcher instead of JsonMatcher, and I can't use any of the cool JSON matcher…

```php
$expectedJsonMatcher = <<<JSON
    {
        "aws": {
            "key": "laclédepassepartout",
            "secret": "lesecretdupèrefouras",
            "@...@"
        }
    }
    JSON;


$matcher = new PHPMatcher;
$hasMatched = $matcher->match($actualJson, $expectedJsonMatcher);
```

> Type pattern "@...@" is not supported by TextMatcher.

Is there a way to force JSON matcher ?

**Comment by norberttech** [comment]
Hey, your example does not have a valid JSON, because of that PHPMatcher thinks this is just a regular text.
The following line is not correct from a json point of view. 

```diff
{
        "aws": {
            "key": "laclédepassepartout",
            "secret": "lesecretdupèrefouras",
-            "@...@"
        }
    }
```

**Comment by tentacode** [comment]
Hey, it's not the Json, but the Json **Pattern**, the Json is ok in the variable `$actualJson`.

It should work when I read the documentation the `@...@` should be supported.

https://github.com/coduo/php-matcher#json-matching-with-unbounded-arrays-and-objects

## Json matching with unbounded arrays and objects

```php
<?php

use Coduo\PHPMatcher\PHPMatcher;

$matcher = new PHPMatcher();

$matcher->match(
  '{
    "users":[
      {
        "firstName": "Norbert",
        "lastName": "Orzechowicz",
        "created": "2014-01-01",
        "roles":["ROLE_USER", "ROLE_DEVELOPER"],
        "attributes": {
          "isAdmin": false,
          "dateOfBirth": null,
          "hasEmailVerified": true
        },
        "avatar": {
          "url": "http://avatar-image.com/avatar.png"
        }
      },
      {
        "firstName": "Michał",
        "lastName": "Dąbrowski",
        "created": "2014-01-01",
        "roles":["ROLE_USER", "ROLE_DEVELOPER", "ROLE_ADMIN"],
        "attributes": {
          "isAdmin": true,
          "dateOfBirth": null,
          "hasEmailVerified": true
        },
        "avatar": null
      }
    ]
  }',
  '{
    "users":[
      {
        "firstName": "@string@",
        "lastName": "@string@",
        "created": "@string@.isDateTime()",
        "roles": [
            "ROLE_USER",
            "@...@"
        ],
        "attributes": {
          "isAdmin": @boolean@,
          "@*@": "@*@"
        },
        "avatar": "@json@.match({\"url\":\"@string@.isUrl()\"})"
      }
      ,
      @...@
    ]
  }'
);
```

**Comment by domis86** [comment]
@tentacode can you try like this? : 

```
$expectedJsonMatcher = <<<JSON
    {
        "aws": {
            "key": "laclédepassepartout",
            "secret": "lesecretdupèrefouras",
            "@*@": "@*@"
        }
    }
    JSON;
```

**Comment by norberttech** [comment]
@domis86 is right here, you should use "@*@" if you just want wildcard, `@...@` was made for arrays, not properties. 

[Example](https://php-matcher.norbert.tech/?form%5Bvalue%5D=%7B%0D%0A++++%22aws%22%3A+%7B%0D%0A++++++++%22key%22%3A+%22test+test%22%2C%0D%0A++++++++%22secret%22%3A+%22asdassfasfasfafs%22%2C%0D%0A++++++++%22something%22%3A+%22more%22%0D%0A++++%7D%0D%0A%7D&form%5Bpattern%5D=%7B%0D%0A++++%22aws%22%3A+%7B%0D%0A++++++++%22key%22%3A+%22%40string%40%22%2C%0D%0A++++++++%22secret%22%3A+%22%40string%40%22%2C%0D%0A++++++++%22%40*%40%22%3A+%22%40*%40%22%0D%0A++++%7D%0D%0A%7D&form%5Bmatch%5D=)

There is also no such thing as "Json Pattern", in order to match value against pattern, json matcher must turn both of them into arrays, it's impossible to achieve that when pattern is not even a JSON.
