### ISSUE TITLE
Support for nullable array wrapping nullable property

### ISSUE THREAD

**Issue by GeLoLabs** [coduo/php-matcher#492]
Hello,

First thank you for your free time on this library.

Given the following PHP structure:

``` php
[
  "property" => null
]
```

or

``` php
[
  "property" => [
     "field" => "value"
  ]
]
```

or

``` php
[
  "property" => [
     "field" => null
  ]
]
```

If I try to validate them with the following pattern, I would expect it to match for all cases but it does not:

```
['property' => '@null@||@array@.match({"field": "@string@||@null@"})']
```

The issue comes from the "OrMatcher" which does a simple explode on the string using the "||" delimiter.

Not sure if it is supposed to be supported or not. Let's first discuss this before looking for a possible fix.

Unfortunately, for now, I was not able to find a way to cover my use case.

**Comment by norberttech** [comment]
hey, `@null@||@array@` should be totally supported, looks like you nailed that bug! Thanks for taking the initiative and fixing it, much appreciated!

**Comment by GeLoLabs** [comment]
I'm not sure how this issue should be fixed as I don't know what should be supported in the OrMatcher. 

Currently, the matcher does a simple explode on the pattern using "||" as delimiter and so, in my example, it ends with:

```
[
    '@null@', 
    '@array@.match({"field": "@string@', 
    '@null@"})'
]
```

instead of

```
[
    '@null@', 
    '@array@.match({"field": "@string@||@null@"})'
]
```

Both, "canMatch" and "match" methods on the OrMatcher needs a fix.

We can try to use regex here and only match top level "||" and exclude those which are in a "match()" expander ? But is there other pattern / expanders which need to be supported ?

**Comment by norberttech** [comment]
Hey, 
I'm sorry I misunderstood your original issue, here is the correct answer, broken into steps. 

**Step 1**: In general, we need to start from creating a pattern that will allow "property" to be an array or null type. 

`{"property": "@null@||@array@"}` 

**Step 2** Now we should make sure that when "property" is an array it has "field" property

`{"property": "@null@||@array@.hasProperty(\"field\")"}` 

**Step 3** Finally we want to allow "field" to be one of `["value", null]`, so we can use oneOf expander with inArray expanders inside. 

`{"property": "@null@||@array@.hasProperty(\"field\").oneOf(inArray(\"value\"), inArray(null))"}` 

Here is a full code example: 

```php
<?php

use Coduo\PHPMatcher\PHPMatcher;

require_once __DIR__ . '/../vendor/autoload.php';

$matcher = new PHPMatcher();

$examples = [
    '{"property": null}', // true
    '{"property": {"field": "value"}}', // true
    '{"property": {"field": null}}', // true
    '{"property": {"field": "something else"}}',
];

$pattern = '{"property": "@null@||@array@.hasProperty(\"field\").oneOf(inArray(\"value\"), inArray(null))"}';

foreach ($examples as $example) {
    $result = $matcher->match($example, $pattern);

    echo ($result ? 'match' : 'no match') . ' - ' . $example . PHP_EOL;
}
```

And the output: 

```bash
match - {"property": null}
match - {"property": {"field": "value"}}
match - {"property": {"field": null}}
no match - {"property": {"field": "something else"}}
```

I'm closing this issue since there is nothing really to fix here, in case of any additional questions feel free to comment in this one or open a new issue.

**Comment by GeLoLabs** [comment]
I understand your approach but IMHO, this is not very DX and becomes very verbose on complex substructure. It would be much more DX to support "||" in substructure but as I pointed out it's not so trivial to implement.

By the way, your example covers a simple property in a substructure what about if I have more than one field ? Can I chain "hasProperty" after the "oneOf" ?

**Comment by norberttech** [comment]
> I understand your approach but IMHO, this is not very DX and becomes very verbose on complex substructure. 

That's a general problem with writing complicated nested patterns. I don't think there is any easy way to make it more user-friendly. I'm totally open to suggestions here, but using regex is not an option - matcher is using lexer because regexes would be too complicated to prepare and maintain later. 

My approach is to match the value against multiple patterns.
